<?php

namespace Extranet\UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('u')
                        ->join('u.groups', 'g')
                        ->select('u, g')
                        ->getQuery()
                        ->getArrayResult()
        ;
    }

    public function findByEmail($email)
    {
        return $this->createQueryBuilder('u')
                        ->join('u.groups', 'g')
                        ->select('u, g')
                        ->where('u.email = :email')
                        ->setParameter('email', $email)
                        ->getQuery()
                        ->getOneOrNullResult()
        ;
    }
}
