extranet_document:
    resource: "@ExtranetDocumentBundle/Resources/config/routing.yml"
    prefix:   /

extranet_media:
    resource: "@ExtranetMediaBundle/Resources/config/routing.yml"
    prefix:   /

extranet_utilisateur:
    resource: "@ExtranetUtilisateurBundle/Resources/config/routing/base.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /moncompte

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /moncompte

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"