<?php

namespace Extranet\ConcoursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends EntityRepository
{
   
        
}
